# this could also be "none" but allows for including atari include files which are guarded
target: atari
compiler: cc65

config_file: "./base.cfg"

# setup files for a basic application
src_files:
  - ./crt0.s

asm_include_paths:
  - ${WS_ROOT}
  - ${WS_ROOT}/atari/src/include
  - ${WS_ROOT}/common/inc
